#!/usr/bin/env python3
"""
gen_app_dispatch.py

Generates per-application dispatch glue from a PSP root + app signal CSV.
Does NOT generate encode C files (those live in libpsp.so).

Usage:
  python3 tools/gen_app_dispatch.py \\
      --psp-root $PSP_ROOT \\
      --csv config/demo_signals.csv \\
      --out protos/

What it does:
  1. Scan $PSP_ROOT for psp_manifest.json files in any subdirectory
  2. Build a unified signal registry
  3. Read app CSV (signal_name,pdu_name  or  signal_name,message_name)
  4. Validate each CSV entry; warn if not found
  5. Group selected signals by PDU/message → dispatch entries
  6. Copy relevant .pb.h and .pb.c from $PSP_ROOT/proto/ to --out dir
  7. Generate:
     - dispatch_table.h   (cmp_lookup / cmp_can_lookup inlines, externs)
     - dispatch_table.c   (static tables using function pointers from libpsp.so)
     - hercules_filter.h  (constexpr slot list + CAN-ID list)
     - ns_wrapper.h       (C++ typedefs for selected types)
"""

from __future__ import annotations

import csv
import json
import os
import shutil
import sys
from typing import Any, Dict, List, Optional, Tuple

try:
    from jinja2 import Environment, DictLoader
except ImportError:
    sys.exit("ERROR: jinja2 is required.  Run: pip install jinja2")


# ---------------------------------------------------------------------------
# Jinja2 templates (inline — generated files are small)
# ---------------------------------------------------------------------------

_DISPATCH_TABLE_H = """\
/* AUTO-GENERATED by gen_app_dispatch.py — DO NOT EDIT */
#pragma once
#include "cmp_plugin.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FlexRay: resolved at runtime via PspLoader / libpsp.so.
 * cmp_lookup / cmp_can_lookup live as static inlines in cmp_plugin.h —
 * don't re-define them here or the C compiler errors on redefinition. */
const cmp_dispatch_entry_t* cmp_get_dispatch_table(void);
size_t                       cmp_get_dispatch_count(void);
const char*                  cmp_get_fibex_version(void);

/* CAN: resolved at runtime via PspLoader / libpsp.so */
const cmp_can_dispatch_entry_t* cmp_can_get_dispatch_table(void);
size_t                           cmp_can_get_dispatch_count(void);
const char*                      cmp_can_get_namespace(void);

/* Per-app extern declarations for selected encode functions.
 * The encode symbols live in libpsp.so; we link/dlopen at runtime. */
{% for fn in fr_encode_fns %}
extern size_t {{ fn }}(const uint8_t*, size_t, uint8_t*, size_t);
{% endfor %}
{% for fn in can_encode_fns %}
extern size_t {{ fn }}(const uint8_t*, size_t, uint8_t*, size_t);
{% endfor %}

#ifdef __cplusplus
}
#endif
"""

_DISPATCH_TABLE_C = """\
/* AUTO-GENERATED by gen_app_dispatch.py — DO NOT EDIT */
#include "dispatch_table.h"
#include <stddef.h>

/* cmp_plugin.h defines cmp_dispatch_entry_t with 9 fields:
 *   slot_id, channel_idx, pdu_name, proto_type,
 *   encode, decode, pdu_byte_offset, pdu_byte_length, proto_buf_max
 *
 * For RX-only applications (the typical case for an app dispatch
 * table) we initialise decode to NULL. Apps that need TX can replace
 * NULL with the matching cmp_decode_* symbol after edit. */
{% if fr_entries %}
static const cmp_dispatch_entry_t _fr_table[] = {
{% for e in fr_entries %}
    { {{ e.slot_id }}u, {{ e.channel_idx }}u, "{{ e.pdu_name }}", "{{ e.proto_type }}",
      {{ e.encode_fn }}, NULL, {{ e.pdu_byte_offset }}u, {{ e.pdu_byte_length }}u, {{ e.proto_buf_max }}u },
{% endfor %}
};

const cmp_dispatch_entry_t* cmp_get_dispatch_table(void) { return _fr_table; }
size_t                       cmp_get_dispatch_count(void) {
    return sizeof(_fr_table) / sizeof(_fr_table[0]);
}
const char* cmp_get_fibex_version(void) { return "{{ fibex_version }}"; }
{% else %}
static const cmp_dispatch_entry_t _fr_table[1];  /* empty */
const cmp_dispatch_entry_t* cmp_get_dispatch_table(void) { return _fr_table; }
size_t                       cmp_get_dispatch_count(void) { return 0; }
const char*                  cmp_get_fibex_version(void)  { return ""; }
{% endif %}

{% if can_entries %}
static const cmp_can_dispatch_entry_t _can_table[] = {
{% for e in can_entries %}
    { 0x{{ '%Xu' % e.can_id }}, {{ 1 if e.is_extended else 0 }}u, "{{ e.message_name }}",
      "{{ e.proto_type }}", {{ e.encode_fn }},
      {{ e.dlc }}u, {{ e.proto_buf_max }}u },
{% endfor %}
};

const cmp_can_dispatch_entry_t* cmp_can_get_dispatch_table(void) { return _can_table; }
size_t                           cmp_can_get_dispatch_count(void) {
    return sizeof(_can_table) / sizeof(_can_table[0]);
}
const char* cmp_can_get_namespace(void) { return "{{ can_namespace }}"; }
{% else %}
static const cmp_can_dispatch_entry_t _can_table[1];  /* empty */
const cmp_can_dispatch_entry_t* cmp_can_get_dispatch_table(void) { return _can_table; }
size_t                           cmp_can_get_dispatch_count(void) { return 0; }
const char*                      cmp_can_get_namespace(void)      { return ""; }
{% endif %}
"""

_HERCULES_FILTER_H = """\
// AUTO-GENERATED by gen_app_dispatch.py — DO NOT EDIT
// Send to Hercules to limit FlexRay capture to used slots.
#pragma once
#include <stdint.h>
#include <stddef.h>

{% if fr_slots %}
static const uint16_t kHerculesFilterSlots[] = { {{ fr_slots | join(', ') }} };
static const size_t   kHerculesFilterSlotCount = {{ fr_slots | length }};
{% else %}
static const uint16_t kHerculesFilterSlots[] = {};
static const size_t   kHerculesFilterSlotCount = 0;
{% endif %}

{% if can_ids %}
static const uint32_t kCanFilterIds[] = { {{ can_ids | join(', ') }} };
static const size_t   kCanFilterIdCount = {{ can_ids | length }};
{% else %}
static const uint32_t kCanFilterIds[] = {};
static const size_t   kCanFilterIdCount = 0;
{% endif %}
"""

_NS_WRAPPER_H = """\
// AUTO-GENERATED by gen_app_dispatch.py — DO NOT EDIT
// C++ typedefs for selected nanopb POD types
#pragma once
{% for inc in pb_includes %}
#include "{{ inc }}"
{% endfor %}

{% for ns, types in namespaces.items() %}
namespace {{ ns }} {
{% for t in types %}
    using {{ t }} = ::{{ ns }}_{{ t }};
{% endfor %}
} // namespace {{ ns }}
{% endfor %}
"""


# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------

def scan_manifests(psp_root: str) -> List[Dict[str, Any]]:
    """Walk psp_root recursively and load every psp_manifest.json found."""
    manifests: List[Dict[str, Any]] = []
    for dirpath, _dirs, files in os.walk(psp_root):
        for fname in files:
            if fname == 'psp_manifest.json':
                path = os.path.join(dirpath, fname)
                try:
                    with open(path, encoding='utf-8') as f:
                        data = json.load(f)
                    data['_manifest_path'] = path
                    data['_manifest_dir']  = dirpath
                    manifests.append(data)
                    print(f"  manifest: {path}")
                except Exception as exc:
                    print(f"  WARNING: Could not read {path}: {exc}", file=sys.stderr)
    return manifests


def build_registry(manifests: List[Dict[str, Any]]) -> Dict[str, Dict[str, Dict[str, Any]]]:
    """
    Build a per-bus container registry:
        {'flexray': {pdu_name: info}, 'can': {message_name: info}}

    Two reasons we keep buses separate:
      (1) A single PDU can appear on multiple (slot, channel) tuples in
          a FlexRay cluster — same PDU re-transmitted on multiple slots
          and/or on both channels A (0) and B (1). We aggregate
          placements into a list so dispatch_table.c can emit one row
          per (slot, channel) tuple. cmp_lookup keys on (slot, ch) and
          silently drops any tuple not in the table, so collapsing to
          a single row would drop packets on the omitted tuples.
      (2) A FlexRay PDU and a CAN message can share a name (e.g.
          ACC_07 lives on both KomfortCAN and the FlexRay cluster in
          Vehicle_Gen2). The CSV's column header (pdu_name vs.
          message_name) tells us which bus the operator meant.
    """
    registry: Dict[str, Dict[str, Dict[str, Any]]] = {'flexray': {}, 'can': {}}

    for m in manifests:
        ns = m.get('namespace', '')
        gen = m.get('generator', '')
        mdir = m.get('_manifest_dir', '')

        if gen == 'fibex_to_nanopb':
            fr_reg = registry['flexray']
            for pdu in m.get('pdus', []):
                pname = pdu.get('pdu_name', '')
                if not pname:
                    continue
                placement = {
                    'slot_id':         pdu.get('slot_id', 0),
                    'channel_idx':     pdu.get('channel_idx', 0),
                    'pdu_byte_offset': pdu.get('pdu_byte_offset', 0),
                    'pdu_byte_length': pdu.get('pdu_byte_length', 0),
                }
                if pname in fr_reg:
                    fr_reg[pname]['placements'].append(placement)
                    continue
                fr_reg[pname] = {
                    'type':           'flexray',
                    'namespace':      ns,
                    'proto_type':     pdu.get('proto_type', f"{ns}.{pname}"),
                    'encode_fn':      pdu.get('encode_fn', f"cmp_encode_{ns}_{pname}"),
                    'placements':     [placement],
                    'manifest_dir':   mdir,
                    'fibex_version':  m.get('fibex_version', ''),
                }

        elif gen == 'can_to_nanopb':
            can_reg = registry['can']
            for msg in m.get('messages', []):
                mname = msg.get('message_name', '')
                if not mname:
                    continue
                can_reg[mname] = {
                    'type':         'can',
                    'namespace':    ns,
                    'proto_type':   msg.get('proto_type', f"{ns}.{mname}"),
                    'encode_fn':    msg.get('encode_fn', f"cmp_can_encode_{ns}_{mname}"),
                    'can_id':       msg.get('can_id', 0),
                    'dlc':          msg.get('dlc', 8),
                    'is_extended':  False,
                    'manifest_dir': mdir,
                }

    return registry


# ---------------------------------------------------------------------------
# CSV loading
# ---------------------------------------------------------------------------

def load_csv(csv_path: str) -> List[Tuple[str, str, str]]:
    """Returns list of (signal_name, container_name, kind_hint).
    kind_hint is 'flexray' if the CSV column was pdu_name, 'can' if
    message_name, '' if unknown (legacy format). The hint resolves
    cross-bus name collisions (e.g. ACC_07 exists on both FlexRay and
    CAN in Vehicle_Gen2)."""
    rows: List[Tuple[str, str, str]] = []
    with open(csv_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            sig = row.get('signal_name', '').strip()
            # Prefer pdu_name (FlexRay) over message_name (CAN); the
            # hint records which column actually supplied the value
            # so cross-bus collisions resolve consistently.
            pdu = row.get('pdu_name', '').strip()
            msg = row.get('message_name', '').strip()
            container = pdu or msg
            hint = 'flexray' if pdu else ('can' if msg else '')
            if sig and container:
                rows.append((sig, container, hint))
    return rows


# ---------------------------------------------------------------------------
# Resolve selected containers
# ---------------------------------------------------------------------------

def resolve_selections(
    csv_rows: List[Tuple[str, str, str]],
    registry: Dict[str, Dict[str, Dict[str, Any]]],
) -> Dict[str, Dict[str, Any]]:
    """
    Returns {container_name: registry_entry} for all containers
    referenced in the CSV. Warns on containers not found.

    kind_hint resolves cross-bus name collisions: 'flexray' selects
    the PDU side, 'can' the message side, '' tries flexray first then
    falls back to can (legacy CSV format without an explicit column).
    """
    selected: Dict[str, Dict[str, Any]] = {}
    fr_reg  = registry.get('flexray', {})
    can_reg = registry.get('can', {})
    for sig_name, container, hint in csv_rows:
        entry: Optional[Dict[str, Any]] = None
        if hint == 'flexray':
            entry = fr_reg.get(container)
        elif hint == 'can':
            entry = can_reg.get(container)
        else:
            entry = fr_reg.get(container) or can_reg.get(container)
        if entry is None:
            print(f"  WARNING: '{container}' not found in PSP "
                  f"{hint or 'any-bus'} registry (signal: {sig_name})",
                  file=sys.stderr)
            continue
        selected[container] = entry
    return selected


# ---------------------------------------------------------------------------
# Proto file copy
# ---------------------------------------------------------------------------

def copy_proto_files(psp_root: str, container_names: List[str], out_dir: str) -> None:
    """
    Copy .pb.h and .pb.c for selected containers from $PSP_ROOT/proto/
    (and any subdirectory) to out_dir.
    """
    copied = 0
    for root, _dirs, files in os.walk(psp_root):
        for fname in files:
            if not (fname.endswith('.pb.h') or fname.endswith('.pb.c')):
                continue
            stem = fname.replace('.pb.h', '').replace('.pb.c', '')
            if stem in container_names:
                src = os.path.join(root, fname)
                dst = os.path.join(out_dir, fname)
                shutil.copy2(src, dst)
                print(f"  copied: {fname}")
                copied += 1
    if copied == 0:
        print("  (no .pb.h/.pb.c files found; run generate.sh in the PSP repo first)")


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

def generate(psp_root: str, csv_path: str, out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)

    # 1. Scan for manifests
    print(f"Scanning PSP root: {psp_root}")
    manifests = scan_manifests(psp_root)
    if not manifests:
        print("  WARNING: No psp_manifest.json files found. "
              "Run generate.sh in the PSP repo first.", file=sys.stderr)

    # 2. Build registry
    registry = build_registry(manifests)
    print(f"  Registry: {len(registry)} containers")

    # 3. Load CSV
    print(f"Loading CSV: {csv_path}")
    csv_rows = load_csv(csv_path)
    print(f"  {len(csv_rows)} rows")

    # 4. Resolve
    selected = resolve_selections(csv_rows, registry)
    if not selected:
        print("WARNING: No containers resolved from CSV. "
              "Check that psp_manifest.json files are present.", file=sys.stderr)

    # 5. Build dispatch entries
    fr_entries:   List[Dict[str, Any]] = []
    can_entries:  List[Dict[str, Any]] = []
    fr_slots:     List[int] = []
    can_ids:      List[int] = []
    fibex_version = ''
    can_namespace = ''

    for cname, info in selected.items():
        if info['type'] == 'flexray':
            if info.get('fibex_version'):
                fibex_version = info['fibex_version']
            # Emit one dispatch row per (slot, channel) placement —
            # cmp_lookup keys on (slot, ch) and silently drops any
            # tuple not present in _fr_table, so a single-row-per-PDU
            # table would lose every packet on the omitted tuples.
            for p in info.get('placements', []):
                slot = p['slot_id']
                if slot not in fr_slots:
                    fr_slots.append(slot)
                fr_entries.append({
                    'pdu_name':        cname,
                    'slot_id':         p['slot_id'],
                    'channel_idx':     p['channel_idx'],
                    'pdu_byte_offset': p['pdu_byte_offset'],
                    'pdu_byte_length': p['pdu_byte_length'],
                    'proto_type':      info['proto_type'],
                    'encode_fn':       info['encode_fn'],
                    'proto_buf_max':   p['pdu_byte_length'] * 2 + 16,
                })
        else:  # can
            cid = info['can_id']
            if cid not in can_ids:
                can_ids.append(cid)
            if info.get('namespace'):
                can_namespace = info['namespace']
            can_entries.append({
                'message_name':  cname,
                'can_id':        info['can_id'],
                'dlc':           info['dlc'],
                'is_extended':   info.get('is_extended', False),
                'proto_type':    info['proto_type'],
                'encode_fn':     info['encode_fn'],
                'proto_buf_max': info['dlc'] * 2 + 16,
            })

    fr_slots.sort()
    can_ids.sort()

    # 6. Copy .pb.h / .pb.c
    print("Copying proto files…")
    container_names = list(selected.keys())
    copy_proto_files(psp_root, container_names, out_dir)

    # 7. Render templates
    loader = DictLoader({
        'dispatch_table.h': _DISPATCH_TABLE_H,
        'dispatch_table.c': _DISPATCH_TABLE_C,
        'hercules_filter.h': _HERCULES_FILTER_H,
        'ns_wrapper.h': _NS_WRAPPER_H,
    })
    env = Environment(loader=loader, keep_trailing_newline=True, trim_blocks=False)

    # Gather namespace → type list for ns_wrapper
    ns_types: Dict[str, List[str]] = {}
    for cname, info in selected.items():
        ns = info.get('namespace', '')
        if ns:
            ns_types.setdefault(ns, []).append(cname)

    pb_includes = [f"{cname}.pb.h" for cname in selected]

    # The dispatch table can have N>1 rows per PDU (one per
    # placement), but each cmp_encode_* symbol should only be
    # forward-declared once. Dedupe the encode-function names.
    seen: set = set()
    fr_encode_fns: List[str] = []
    for e in fr_entries:
        if e['encode_fn'] not in seen:
            seen.add(e['encode_fn'])
            fr_encode_fns.append(e['encode_fn'])
    seen.clear()
    can_encode_fns: List[str] = []
    for e in can_entries:
        if e['encode_fn'] not in seen:
            seen.add(e['encode_fn'])
            can_encode_fns.append(e['encode_fn'])

    ctx: Dict[str, Any] = {
        'fr_entries':    fr_entries,
        'can_entries':   can_entries,
        'fr_encode_fns': fr_encode_fns,
        'can_encode_fns':can_encode_fns,
        'fr_slots':      fr_slots,
        'can_ids':       can_ids,
        'fibex_version': fibex_version,
        'can_namespace': can_namespace,
        'namespaces':    ns_types,
        'pb_includes':   pb_includes,
    }

    for tmpl_name in ('dispatch_table.h', 'dispatch_table.c',
                      'hercules_filter.h', 'ns_wrapper.h'):
        out_path = os.path.join(out_dir, tmpl_name)
        tmpl = env.get_template(tmpl_name)
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(tmpl.render(**ctx))
        print(f"  wrote: {out_path}")

    print("\n--- Summary ---")
    # Count distinct PDUs by encode_fn (matches one extern per PDU).
    fr_pdu_count = len({e['encode_fn'] for e in fr_entries})
    print(f"  FlexRay : {fr_pdu_count} PDU(s) → {len(fr_entries)} dispatch row(s) "
          f"across slots {fr_slots}")
    print(f"  CAN     : {len(can_entries)} entries, IDs: {[hex(i) for i in can_ids]}")
    print("Done.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

