"""Generate the AUTOSAR-side bus wiring from per-bus catalogs.

Each bus catalog (FIBEX or DBC) already produced a per-bus
``<bus>/package.art`` (the importer: ``message <Pdu> { ... }`` decls).
This generator adds the WIRING layer next to it, plus a thin aggregator:

  - ``<bus>/component.art``  (one per bus) carries:
      * one ``interface senderReceiver <Pdu>_Iface { data <Pdu> record }``
        per PDU — co-located with the message it carries, so the `data`
        cross-reference resolves WITHIN the bus package (no ambiguity even
        when the same PDU name exists on another bus).
      * ``node atomic <Bus>_Bus { ports { sender pdu_<x> provides
        <Pdu>_Iface ... } }`` — the bus mega-node, exporting one sender
        port per PDU. Bare iface names resolve because the node and the
        ifaces share the bus package (after the loader merges
        package.art ⊕ component.art).

  - ``system.art``  (the aggregator) is now a THIN PLACEHOLDER: it only
    ``import``s each bus sub-package so a consumer entering via
    ``system.art`` discovers the buses recursively. It no longer
    re-exports interfaces or hosts the bus nodes — those live in the bus
    sub-packages where their messages are.

Why a "bus" is modeled as a node: the grammar's `port` construct lives
inside `node atomic`. There is no top-level `port`. The bus node hosts
the per-PDU sender ports. Its TIPC address is synthetic (a bus owns no
TIPC endpoint) — a high-bit prefix makes that obvious.

Consumers (apps) reference a bus iface through an import:

    import system.autosar.mlbevo_gen2.flexray.*
    receiver eml requires EML_01_Iface                  // bare if unique
    receiver lh  requires system.autosar.mlbevo_gen2.flexray.Licht_hinten_01_Iface
                                                        // FQN to disambiguate
"""
from __future__ import annotations

import json
from pathlib import Path


# ---------------------------------------------------------------------------
# per-bus component.art (the bus mega-NODE only — no per-PDU ports)
# ---------------------------------------------------------------------------
#
# Why node-only (no `sender pdu_<x> provides <Pdu>_Iface` per PDU): a bus has
# 512 (kcan) / 1025 (flexray) PDUs. Eagerly declaring one iface + one node port
# per PDU is O(N²) to parse+resolve (textX same-package cross-ref scan — measured
# ~15s for flexray) and pointless: (a) the per-PDU <Pdu>_Iface / message types
# already resolve LAZILY from this dir's catalog.json (the scope provider's fast
# path — O(1), it parses only the one PDU stub a ref actually needs), and (b) the
# gateway routes decoded PDUs by the catalog→netgraph LUT at runtime
# (CmpGwService casts to kcan_bus's tipc addr), NOT through .art sender ports.
# So component.art carries ONLY the node + its synthetic TIPC address — the one
# thing that ISN'T catalog-resolvable (nodes aren't, per scope.py) and that the
# gateway forward-declares `extern`.

_BUS_TIPC_BASE = 0x9F000000  # synthetic; a bus owns no real TIPC endpoint


def _bus_node_name(bus: str) -> str:
    """`kcan` -> `Kcan_Bus`, `flexray` -> `Flexray_Bus`."""
    return f"{bus[:1].upper()}{bus[1:]}_Bus"


def _emit_bus_component_art(package_name: str, bus: str, bus_index: int) -> str:
    """The bus's component.art: JUST the `<Bus>_Bus` mega-node + its synthetic
    TIPC address. No per-PDU ifaces or ports (those resolve lazily via this
    dir's catalog.json; the gateway routes per-PDU via the netgraph LUT). This
    is the real def the gateway's `extern node atomic <Bus>_Bus { }` resolves
    to — co-located with the bus's package.art message decls."""
    bus_pkg = f"{package_name}.{bus}"
    node = _bus_node_name(bus)
    addr = _BUS_TIPC_BASE + bus_index
    return (
        "// AUTO-GENERATED by `artheia gen-autosar-system` — DO NOT EDIT.\n"
        "//\n"
        f"// The `{node}` bus mega-node for bus `{bus}` (synthetic TIPC addr;\n"
        "// a bus owns no real endpoint). NODE-ONLY by design: the per-PDU\n"
        "// <Pdu>_Iface / message types resolve LAZILY from this dir's\n"
        "// catalog.json (O(1), no N² eager scan), and the gateway routes PDUs\n"
        "// via the catalog→netgraph LUT at runtime — not through .art ports.\n"
        "// Senders (the gateway) forward-declare this node `extern`; the\n"
        "// resolver substitutes this real body via the import.\n"
        "\n"
        f"package {bus_pkg}\n"
        "\n"
        f"node atomic {node} {{ tipc type=0x{addr:08x} instance=0 }}\n"
    )


# ---------------------------------------------------------------------------
# thin aggregator system.art (imports each bus; no re-export)
# ---------------------------------------------------------------------------


def _emit_system_art(package_name: str, bus_names: list[str]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by `artheia gen-autosar-system` — DO NOT EDIT.")
    lines.append("//")
    lines.append("// Thin aggregator: imports each bus sub-package so a consumer")
    lines.append("// entering via this file discovers every bus recursively. The")
    lines.append("// real schema (messages, typed interfaces) and the bus mega-nodes")
    lines.append("// live in the per-bus sub-packages (package.art ⊕ component.art),")
    lines.append("// next to the PDU messages they carry. Nothing is re-exported here.")
    lines.append("")
    lines.append(f"package {package_name}")
    lines.append("")
    for bus in bus_names:
        lines.append(f"import {package_name}.{bus}.*")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def generate(
    catalog_paths: list[str | Path],
    out_path: str | Path,
    package_name: str,
) -> Path:
    """Read each catalog and emit the bus wiring.

    For each catalog (one per bus):
      - write ``<system.art dir>/<bus>/component.art`` (ifaces + bus node),
        sitting beside the importer's ``<bus>/package.art`` message decls.
    Then write the thin aggregator at *out_path* (``system.art``).

    `catalog_paths` is a list of per-bus catalog.json files.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sys_dir = out_path.parent

    catalogs: list[dict] = []
    for p in catalog_paths:
        catalogs.append(json.loads(Path(p).read_text()))

    bus_names = [cat["bus"] for cat in catalogs]

    # Per-bus component.art: the `<Bus>_Bus` mega-NODE only (no per-PDU ifaces
    # or ports — those resolve lazily from catalog.json, and the per-PDU eager
    # form is O(N²) to parse). This is the real def the gateway's `extern node
    # atomic <Bus>_Bus { }` resolves to (nodes aren't catalog-resolvable). The
    # system.art aggregator then just imports each bus so consumers discover
    # the node.
    for bus_index, cat in enumerate(catalogs):
        bus = cat["bus"]
        comp_path = sys_dir / bus / "component.art"
        comp_path.parent.mkdir(parents=True, exist_ok=True)
        comp_path.write_text(
            _emit_bus_component_art(package_name, bus, bus_index))
        print(f"  wrote: {comp_path}  ({_bus_node_name(bus)} node; "
              f"{len(cat.get('messages', {}))} PDUs stay catalog-lazy)")

    out_path.write_text(_emit_system_art(package_name, bus_names))
    print(f"  wrote: {out_path}  (thin aggregator; imports each bus)")
    return out_path
