"""Generate the AUTOSAR-side system .art: one mega-node per bus.

Each bus catalog (FIBEX or DBC) becomes a `node atomic <Bus>_Bus { }`
in the emitted system.art, with one `sender` port per PDU. Downstream
compositions (gateway/system, platform/system) prototype these buses
and wire their ports to receivers.

Why a "bus" is modeled as a node:

The artheia grammar's `port` construct lives inside `node atomic`.
There is no top-level `port` declaration. To expose the per-PDU
sender ports we need a node host, even though a bus is not really a
node in the CAUS/AUTOSAR sense. The shape is intentional: it lets the
.art typecheck cleanly without changing the grammar.

Output shape:

    package <package_name>

    interface senderReceiver EML_01_Iface { }
    interface senderReceiver ACC_06_Iface { }
    ...

    node atomic Mlbevo_Gen2_Bus {
        tipc type=0x9... instance=0   // synthetic — bus is wire, not TIPC
        ports {
            sender pdu_eml_01    provides EML_01_Iface
            sender pdu_acc_06    provides ACC_06_Iface
            ...
        }
    }

The TIPC address on the mega-node is synthetic (the bus itself does
not own a TIPC endpoint) but Artheia's grammar requires it. Use a
high-bit prefix to make the synthetic nature obvious.
"""
from __future__ import annotations

import json
import re
from pathlib import Path


_TIPC_BASE = 0x9F000000  # synthetic addresses for AUTOSAR mega-nodes


def _bus_node_name(bus_name: str) -> str:
    """`mlbevo_gen2` -> `Mlbevo_Gen2_Bus`. PascalCase per `_` token."""
    parts = re.split(r"[_\-]", bus_name)
    return "".join(p.capitalize() for p in parts if p) + "_Bus"


def _port_name(pdu_name: str) -> str:
    """PDU name -> port identifier. `BV2_Objekt_01` -> `pdu_bv2_objekt_01`."""
    return "pdu_" + pdu_name.lower()


def _iface_name(pdu_name: str) -> str:
    return f"{pdu_name}_Iface"


def generate(
    catalog_paths: list[str | Path],
    out_path: str | Path,
    package_name: str,
) -> Path:
    """Read each catalog, emit a combined system.art.

    `catalog_paths` is a list of per-bus catalog.json files. One
    `node atomic <Bus>_Bus` is emitted per catalog, plus one
    senderReceiver interface per unique PDU name across all buses
    (PDUs that share a name across buses share an interface decl).
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    catalogs: list[dict] = []
    for p in catalog_paths:
        catalogs.append(json.loads(Path(p).read_text()))

    # Gather PDU names across all buses for the shared interface decls.
    pdu_names: set[str] = set()
    for cat in catalogs:
        pdu_names.update(cat.get("messages", {}).keys())

    lines: list[str] = []
    lines.append("// AUTO-GENERATED by `artheia gen-autosar-system` — DO NOT EDIT.")
    lines.append("//")
    lines.append("// One mega-node per CAN/FlexRay bus exporting a sender port per PDU.")
    lines.append("// Bus addressing (slot/cycle/channel/can_id) lives in the per-bus")
    lines.append("// netgraph.json; downstream tools join symbolic port name with that LUT.")
    lines.append("")
    lines.append(f"package {package_name}")
    lines.append("")

    # Per-PDU sender-receiver interface decls (empty payload — real shape
    # is in catalog.json + per-bus package.art's `message <Pdu>` decls).
    lines.append("// ---- senderReceiver interfaces (one per PDU) ----")
    for name in sorted(pdu_names):
        lines.append(f"interface senderReceiver {_iface_name(name)} {{ }}")
    lines.append("")

    # One mega-node per bus.
    for idx, cat in enumerate(catalogs):
        bus_name = cat["bus"]
        node_name = _bus_node_name(bus_name)
        pdus = sorted(cat.get("messages", {}).keys())
        tipc = _TIPC_BASE + idx
        lines.append(
            f"// ---- {bus_name} ({cat['bus_kind']}, {len(pdus)} PDUs) ----"
        )
        lines.append(f"node atomic {node_name} {{")
        lines.append(
            f"    tipc type=0x{tipc:08x} instance=0   // synthetic — bus, not a real TIPC node"
        )
        lines.append("    ports {")
        for pdu in pdus:
            lines.append(
                f"        sender {_port_name(pdu)} provides {_iface_name(pdu)}"
            )
        lines.append("    }")
        lines.append("}")
        lines.append("")

    content = "\n".join(lines).rstrip() + "\n"
    out_path.write_text(content)

    print(f"  wrote: {out_path}")
    print(f"  buses: {len(catalogs)}  PDUs: {len(pdu_names)}")
    for cat in catalogs:
        bus = cat["bus"]
        n = len(cat.get("messages", {}))
        print(f"    {bus}: {n} ports")
    return out_path
