"""Generate the AUTOSAR-side bus wiring from per-bus catalogs.

Each bus catalog (FIBEX or DBC) already produced a per-bus
``<bus>/package.art`` (the importer: ``message <Pdu> { ... }`` decls).
This generator adds the WIRING layer next to it, plus a thin aggregator:

  - ``<bus>/component.art``  (one per bus) carries:
      * one ``interface senderReceiver <Pdu>_Iface { data <Pdu> record }``
        per PDU — co-located with the message it carries, so the `data`
        cross-reference resolves WITHIN the bus package (no ambiguity even
        when the same PDU name exists on another bus).
      * ``node atomic <Bus>_Bus { ports { sender pdu_<x> provides
        <Pdu>_Iface ... } }`` — the bus mega-node, exporting one sender
        port per PDU. Bare iface names resolve because the node and the
        ifaces share the bus package (after the loader merges
        package.art ⊕ component.art).

  - ``system.art``  (the aggregator) is now a THIN PLACEHOLDER: it only
    ``import``s each bus sub-package so a consumer entering via
    ``system.art`` discovers the buses recursively. It no longer
    re-exports interfaces or hosts the bus nodes — those live in the bus
    sub-packages where their messages are.

Why a "bus" is modeled as a node: the grammar's `port` construct lives
inside `node atomic`. There is no top-level `port`. The bus node hosts
the per-PDU sender ports. Its TIPC address is synthetic (a bus owns no
TIPC endpoint) — a high-bit prefix makes that obvious.

Consumers (apps) reference a bus iface through an import:

    import system.autosar.mlbevo_gen2.flexray.*
    receiver eml requires EML_01_Iface                  // bare if unique
    receiver lh  requires system.autosar.mlbevo_gen2.flexray.Licht_hinten_01_Iface
                                                        // FQN to disambiguate
"""
from __future__ import annotations

import json
from pathlib import Path


# ---------------------------------------------------------------------------
# thin aggregator system.art (imports each bus; no re-export)
# ---------------------------------------------------------------------------


def _emit_system_art(package_name: str, bus_names: list[str]) -> str:
    lines: list[str] = []
    lines.append("// AUTO-GENERATED by `artheia gen-autosar-system` — DO NOT EDIT.")
    lines.append("//")
    lines.append("// Thin aggregator: imports each bus sub-package so a consumer")
    lines.append("// entering via this file discovers every bus recursively. The")
    lines.append("// real schema (messages, typed interfaces) and the bus mega-nodes")
    lines.append("// live in the per-bus sub-packages (package.art ⊕ component.art),")
    lines.append("// next to the PDU messages they carry. Nothing is re-exported here.")
    lines.append("")
    lines.append(f"package {package_name}")
    lines.append("")
    for bus in bus_names:
        lines.append(f"import {package_name}.{bus}.*")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# entry point
# ---------------------------------------------------------------------------


def generate(
    catalog_paths: list[str | Path],
    out_path: str | Path,
    package_name: str,
) -> Path:
    """Read each catalog and emit the bus wiring.

    For each catalog (one per bus):
      - write ``<system.art dir>/<bus>/component.art`` (ifaces + bus node),
        sitting beside the importer's ``<bus>/package.art`` message decls.
    Then write the thin aggregator at *out_path* (``system.art``).

    `catalog_paths` is a list of per-bus catalog.json files.
    """
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sys_dir = out_path.parent

    catalogs: list[dict] = []
    for p in catalog_paths:
        catalogs.append(json.loads(Path(p).read_text()))

    bus_names = [cat["bus"] for cat in catalogs]

    # No per-bus `.art` is emitted for the interfaces or the bus mega-node.
    # The scope provider resolves `<Pdu>_Iface` (and its `data <Pdu>`)
    # lazily from each bus's catalog.json — generating a tiny per-PDU stub
    # on demand — so it never has to parse a thousand-PDU package (textX
    # cross-ref resolution is O(N²) in same-package element count). A bus
    # mega-node with one sender port per PDU would re-introduce that N²,
    # so it is NOT emitted: a sender (e.g. the gateway) declares its own
    # bus node carrying only the ports it actually routes.
    out_path.write_text(_emit_system_art(package_name, bus_names))
    print(f"  wrote: {out_path}  (thin aggregator; ifaces resolve via catalog.json)")
    for cat in catalogs:
        print(f"    {cat['bus']}: {len(cat.get('messages', {}))} PDUs (catalog-indexed)")
    return out_path
