"""Generate dispatch_local.c for libpsp_local.so.

Ported verbatim from gateway/pero_cmp_lnx/tools/gen_codec_dispatch.py — the
output byte-stream must be identical so consumers (pero_cmp_gw_svc, the
apps) keep producing the same artifact.

The output references only the codec functions needed by one application,
so when linked with libcodec.a the linker dead-strips all unreferenced
encode/decode symbols → small libpsp_local.so.
"""
from __future__ import annotations

import csv
import json
import os
import sys
from typing import Dict, List, Optional, Tuple


def _scan_manifests(psp_root: str) -> List[dict]:
    """Recursively find all psp_manifest.json under $psp_root/src/."""
    manifests: List[dict] = []
    src_dir = os.path.join(psp_root, "src")
    for root, _, files in os.walk(src_dir):
        for f in files:
            if f == "psp_manifest.json":
                path = os.path.join(root, f)
                try:
                    with open(path) as fh:
                        manifests.append(json.load(fh))
                except Exception:
                    pass
    return manifests


def _build_registry(manifests: List[dict]) -> Dict[str, list]:
    """Build {message_name → [info, ...]} multimap from all manifests.
    A name may appear in both FlexRay and CAN manifests — include all variants."""
    registry: Dict[str, list] = {}
    for m in manifests:
        for pdu in m.get("pdus", []):
            name = pdu.get("pdu_name") or pdu.get("message_name", "")
            if name:
                registry.setdefault(name, []).append(
                    {"manifest": m, "entry": pdu, "is_flexray": True}
                )
        for msg in m.get("messages", []):
            name = msg.get("message_name", "")
            if name:
                registry.setdefault(name, []).append(
                    {"manifest": m, "entry": msg, "is_flexray": False}
                )
    return registry


def _load_csv(csv_path: str) -> List[str]:
    """Return deduplicated list of PDU/message names from the CSV."""
    names: List[str] = []
    seen: set = set()
    with open(csv_path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            name = (row.get("pdu_name") or row.get("message_name") or "").strip()
            if name and name not in seen:
                seen.add(name)
                names.append(name)
    return names


HEADER = """\
/* AUTO-GENERATED by gen_codec_dispatch.py — DO NOT EDIT */
/*
 * Minimal codec dispatch for libpsp_local.so.
 * Only references the codec functions needed by this application.
 * Link with libcodec.a — linker strips unused encode/decode symbols.
 *
 * Exports the same symbols as libpsp.so so PspLoader works unchanged:
 *   psp_can_lookup(), psp_can_get_buses(), psp_can_get_bus_count(),
 *   cmp_get_dispatch_table(), cmp_get_dispatch_count()
 */
#include <stddef.h>
#include "cmp_plugin.h"
#include "psp_can_registry.h"
"""


def generate(
    psp_root: str,
    csv_path: Optional[str],
    out_dir: str,
    *,
    encode_only: bool = False,
    decode_only: bool = False,
    namespaces: Optional[List[str]] = None,
) -> str:
    """Run the full pipeline. Returns the path to the emitted dispatch_local.c.

    Behavior is byte-identical to the legacy `gen_codec_dispatch.py` so the
    pero_cmp_gw_svc build keeps producing the same artifact.
    """
    if encode_only and decode_only:
        raise ValueError("--encode-only and --decode-only are mutually exclusive")

    print(f"Scanning PSP manifests: {psp_root}")
    manifests = _scan_manifests(psp_root)
    print(f"  found {len(manifests)} manifest(s)")

    selected: Optional[List[str]] = None
    if csv_path:
        selected = _load_csv(csv_path)
        print(f"CSV: {csv_path} → {len(selected)} PDU/message names")

    return _generate(manifests, selected, encode_only, decode_only, out_dir, namespaces)


def _generate(
    manifests: List[dict],
    selected: Optional[List[str]],
    encode_only: bool,
    decode_only: bool,
    out_dir: str,
    namespaces: Optional[List[str]] = None,
) -> str:
    registry = _build_registry(manifests)

    if selected is None:
        selected = list(registry.keys())

    can_entries: List[Tuple[dict, dict]] = []
    fr_entries: List[Tuple[dict, dict]] = []
    not_found: List[str] = []

    for name in selected:
        if name not in registry:
            not_found.append(name)
            continue
        for info in registry[name]:
            if info["is_flexray"]:
                fr_entries.append((info["manifest"], info["entry"]))
            else:
                can_entries.append((info["manifest"], info["entry"]))

    if not_found:
        for n in not_found:
            print(f"  WARNING: {n!r} not found in PSP manifests", file=sys.stderr)

    if namespaces:
        can_entries = [(m, e) for m, e in can_entries if m.get("namespace", "") in namespaces]
        fr_entries = [(m, e) for m, e in fr_entries if m.get("namespace", "") in namespaces]

    def _dedup(entries):
        seen, out = set(), []
        for m, e in entries:
            key = e.get("encode_fn", "") or e.get("pdu_name", e.get("message_name", ""))
            if key not in seen:
                seen.add(key)
                out.append((m, e))
        return out

    can_entries = _dedup(can_entries)
    fr_entries = _dedup(fr_entries)

    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "dispatch_local.c")

    lines = [HEADER, ""]

    if can_entries:
        lines.append("/* ── CAN codec externs ── */")
        for m, e in can_entries:
            ns = m.get("namespace", "")
            name = e.get("message_name", "")
            fn_e = e.get("encode_fn", f"cmp_can_encode_{ns}_{name}")
            fn_d = e.get("decode_fn", f"cmp_decode_{ns}_{name}")
            if not decode_only:
                lines.append(f"extern size_t {fn_e}(const uint8_t*, size_t, uint8_t*, size_t);")
            if not encode_only:
                lines.append(f"extern size_t {fn_d}(const uint8_t*, size_t, uint8_t*, size_t);")
        lines.append("")

    if fr_entries:
        lines.append("/* ── FlexRay codec externs ── */")
        for m, e in fr_entries:
            ns = m.get("namespace", "")
            name = e.get("pdu_name", "")
            fn_e = e.get("encode_fn", f"cmp_encode_{ns}_{name}")
            fn_d = e.get("decode_fn", f"cmp_decode_{ns}_{name}")
            if not decode_only:
                lines.append(f"extern size_t {fn_e}(const uint8_t*, size_t, uint8_t*, size_t);")
            if not encode_only:
                lines.append(f"extern size_t {fn_d}(const uint8_t*, size_t, uint8_t*, size_t);")
        lines.append("")

    if can_entries:
        lines.append("static const cmp_can_dispatch_entry_t _can_local[] = {")
        for m, e in can_entries:
            ns = m.get("namespace", "")
            name = e.get("message_name", "")
            can_id = e.get("can_id", 0)
            dlc = e.get("dlc", 8)
            buf_max = len(selected) * 12 + 16
            fn_e = e.get("encode_fn", f"cmp_can_encode_{ns}_{name}")
            fn_d = e.get("decode_fn", f"cmp_decode_{ns}_{name}")
            enc = fn_e if not decode_only else "(cmp_encode_fn_t)0"
            dec = fn_d if not encode_only else "(cmp_decode_fn_t)0"
            pt = f"{ns}.{name}"
            lines.append(
                f'    {{ 0x{can_id:X}u, 0u, "{name}", "{pt}", '
                f"{enc}, {dec}, {dlc}u, {buf_max}u }},"
            )
        lines.append("};")
        lines.append(
            "static const size_t _can_local_count = "
            "sizeof(_can_local)/sizeof(_can_local[0]);"
        )
        lines.append("")

    if fr_entries:
        lines.append("static const cmp_dispatch_entry_t _fr_local[] = {")
        for m, e in fr_entries:
            ns = m.get("namespace", "")
            name = e.get("pdu_name", "")
            slot = e.get("slot_id", 0)
            ch = e.get("channel_idx", 0)
            off = e.get("pdu_byte_offset", 0)
            blen = e.get("pdu_byte_length", 34)
            buf_max = blen + 16
            fn_e = e.get("encode_fn", f"cmp_encode_{ns}_{name}")
            fn_d = e.get("decode_fn", f"cmp_decode_{ns}_{name}")
            enc = fn_e if not decode_only else "(cmp_encode_fn_t)0"
            dec = fn_d if not encode_only else "(cmp_decode_fn_t)0"
            pt = f"{ns}.{name}"
            lines.append(
                f'    {{ {slot}u, {ch}u, "{name}", "{pt}", '
                f"{enc}, {dec}, {off}u, {blen}u, {buf_max}u }},"
            )
        lines.append("};")
        lines.append(
            "static const size_t _fr_local_count = "
            "sizeof(_fr_local)/sizeof(_fr_local[0]);"
        )
        lines.append("")

    lines.append("/* ── PspLoader-compatible exports ── */")

    if can_entries:
        lines += [
            "const cmp_can_dispatch_entry_t* psp_can_lookup(uint32_t can_id) {",
            "    size_t i;",
            "    for (i = 0; i < _can_local_count; i++)",
            "        if (_can_local[i].can_id == can_id) return &_can_local[i];",
            "    return (const cmp_can_dispatch_entry_t*)0;",
            "}",
            "const cmp_can_dispatch_entry_t* psp_can_decode_lookup(uint32_t can_id) {",
            "    return psp_can_lookup(can_id);",
            "}",
            "",
        ]
    else:
        lines += [
            "const cmp_can_dispatch_entry_t* psp_can_lookup(uint32_t can_id)",
            "    { (void)can_id; return (const cmp_can_dispatch_entry_t*)0; }",
            "const cmp_can_dispatch_entry_t* psp_can_decode_lookup(uint32_t can_id)",
            "    { return psp_can_lookup(can_id); }",
            "",
        ]

    lines += [
        "static const psp_can_bus_t _stub_buses[] = {",
        '    { "local", (void*)0, (void*)0 }',
        "};",
        "const psp_can_bus_t*  psp_can_get_buses(void)     { return _stub_buses; }",
        "size_t                psp_can_get_bus_count(void) { return 1u; }",
        "",
    ]

    if fr_entries:
        lines += [
            "const cmp_dispatch_entry_t* cmp_get_dispatch_table(void)",
            "    { return _fr_local; }",
            "size_t cmp_get_dispatch_count(void) { return _fr_local_count; }",
            'const char* cmp_get_fibex_version(void) { return "local"; }',
            "",
        ]
    else:
        lines += [
            "const cmp_dispatch_entry_t* cmp_get_dispatch_table(void)",
            "    { return (const cmp_dispatch_entry_t*)0; }",
            "size_t cmp_get_dispatch_count(void) { return 0u; }",
            'const char* cmp_get_fibex_version(void) { return "local-can-only"; }',
            "",
        ]

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    mode = (
        "encode-only" if encode_only
        else "decode-only" if decode_only
        else "bidirectional"
    )
    print(f"  wrote: {out_path}")
    print(f"  messages: {len(can_entries)} CAN + {len(fr_entries)} FlexRay  mode={mode}")
    if not_found:
        print(f"  not found: {not_found}")

    return out_path
