"""Generate gw_bus_types.h from PSP manifests.

Produces a stable GwBusId enum (CAN buses 1-127, FlexRay 128+) and a
gw_namespace_to_bus_id() helper, shared between GW and client. Ported
verbatim from gateway/pero_cmp_lnx/tools/gen_gw_types.py — byte-identical
output.
"""
from __future__ import annotations

import json
import os
from typing import List, Tuple


_CAN_ORDER = [
    "can_diagcan",
    "can_dcan",
    "can_hcan",
    "can_ican",
    "can_k2can",
    "can_kcan",
    "can_komfortcan",
    "can_subcan",
]
_FR_BASE = 128


def _scan_namespaces(psp_root: str) -> Tuple[List[str], List[str]]:
    can_ns, fr_ns = set(), set()
    src_dir = os.path.join(psp_root, "src")
    for root, _, files in os.walk(src_dir):
        for f in files:
            if f != "psp_manifest.json":
                continue
            try:
                with open(os.path.join(root, f)) as fh:
                    m = json.load(fh)
                ns = m.get("namespace", "")
                if ns.startswith("can_"):
                    can_ns.add(ns)
                elif ns:
                    fr_ns.add(ns)
            except Exception:
                pass
    return sorted(can_ns), sorted(fr_ns)


def _enum_name(ns: str) -> str:
    return "GW_BUS_" + ns.upper().replace("_", "_", 1)


def generate(psp_root: str, out_dir: str) -> str:
    can_ns, fr_ns = _scan_namespaces(psp_root)
    os.makedirs(out_dir, exist_ok=True)

    all_can = list(_CAN_ORDER)
    for ns in can_ns:
        if ns not in all_can:
            all_can.append(ns)

    lines = [
        "/* AUTO-GENERATED by gen_gw_types.py — DO NOT EDIT */",
        "/* GwBusId: stable bus identifier for GwMessageHeader.can.bus_id / .flexray.bus_id */",
        "#pragma once",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "typedef enum {",
        "    GW_BUS_INVALID = 0,",
        "",
        "    /* ── CAN buses (1-127, stable alphabetical assignment) ── */",
    ]

    for i, ns in enumerate(all_can):
        if ns in can_ns:
            enum = _enum_name(ns)
            lines.append(f"    {enum} = {i + 1},")

    lines += [
        "",
        "    /* ── FlexRay clusters (128+, channel A = base, B = base+1) ── */",
    ]
    for i, ns in enumerate(sorted(fr_ns)):
        base = _FR_BASE + i * 2
        lines.append(f"    {_enum_name(ns)}_A = {base},")
        lines.append(f"    {_enum_name(ns)}_B = {base + 1},")

    lines += [
        "} GwBusId;",
        "",
        '/* Map proto_type namespace prefix (e.g. "can_komfortcan") → GwBusId */',
        "static inline uint8_t gw_namespace_to_bus_id(const char* ns) {",
        "    if (!ns) return (uint8_t)GW_BUS_INVALID;",
    ]
    for i, ns in enumerate(all_can):
        if ns in can_ns:
            enum = _enum_name(ns)
            lines.append(f'    if (strcmp(ns, "{ns}") == 0) return (uint8_t){enum};')
    for i, ns in enumerate(sorted(fr_ns)):
        base = _FR_BASE + i * 2
        enum_a = _enum_name(ns) + "_A"
        lines.append(f'    if (strcmp(ns, "{ns}") == 0) return (uint8_t){enum_a};')
    lines += [
        "    return (uint8_t)GW_BUS_INVALID;",
        "}",
        "",
        '/* Extract namespace from proto_type "namespace.MessageName" → bus_id */',
        "static inline uint8_t gw_proto_type_to_bus_id(const char* proto_type) {",
        "    char ns[32]; const char* dot;",
        "    if (!proto_type) return (uint8_t)GW_BUS_INVALID;",
        "    dot = strchr(proto_type, '.');",
        "    if (!dot) return (uint8_t)GW_BUS_INVALID;",
        "    int n = (int)(dot - proto_type);",
        "    if (n <= 0 || n >= (int)sizeof(ns)) return (uint8_t)GW_BUS_INVALID;",
        "    memcpy(ns, proto_type, (size_t)n); ns[n] = '\\0';",
        "    return gw_namespace_to_bus_id(ns);",
        "}",
        "",
        "#ifdef __cplusplus",
        "}",
        "#endif",
    ]

    path = os.path.join(out_dir, "gw_bus_types.h")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  wrote: {path}")
    print(f"  CAN buses: {[ns for ns in all_can if ns in can_ns]}")
    print(f"  FlexRay:   {sorted(fr_ns)}")
    return path
