"""Per-package proto3 generator: one combined .proto per .art package.

Unlike `proto.py` (which emits one .proto per message), this generator
emits a single .proto file per source package, laid out under the
output root in directories that mirror the package path:

    package demo.system     → <out>/demo/system/system.proto
    package gateway.system  → <out>/gateway/system/system.proto

This matches the runtime convention used by libgw / odd_path_client —
includes are `#include "<pkg-path>/<file>.pb.h"` so the .art package
hierarchy and the C++ include hierarchy stay symmetric.

Field numbering: 1..N in declaration order. Field types follow proto3
scalars verbatim (the .art grammar's PrimitiveType set is a strict
subset of proto3's). References to other messages/enums become
imports (under the same package only, for now).
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List

from textx import metamodel_from_file


_GRAMMAR = (Path(__file__).resolve().parent.parent /
            "grammar" / "artheia.tx")


@dataclass
class _Field:
    name: str
    number: int
    proto_type: str
    repeated: bool


@dataclass
class _Message:
    name: str
    fields: List[_Field]


@dataclass
class _Enum:
    name: str
    values: list


def _proto_type_for(field) -> str:
    t = field.type
    if getattr(t, "ref", None) is not None:
        # Cross-message reference. For the demo all references resolve
        # within the same package, so no import path needed.
        return t.ref.name
    return t.kind


def _harvest(model):
    messages: List[_Message] = []
    enums: List[_Enum] = []
    for el in model.elements:
        kind = el.__class__.__name__
        if kind == "MessageDecl":
            fields = []
            for idx, f in enumerate(el.fields):
                fields.append(_Field(
                    name=f.name,
                    number=idx + 1,
                    proto_type=_proto_type_for(f),
                    repeated=bool(f.repeated),
                ))
            messages.append(_Message(name=el.name, fields=fields))
        elif kind == "EnumDecl":
            enums.append(_Enum(name=el.name, values=el.values))
    return messages, enums


def _render_proto(model, package: str, source_file: str) -> str:
    messages, enums = _harvest(model)
    lines: List[str] = []
    lines.append("// AUTO-GENERATED by `artheia gen-proto-package` — DO NOT EDIT")
    lines.append(f"// source: {source_file}")
    lines.append("")
    lines.append("syntax = \"proto3\";")
    # Proto package: dot-joined from the .art package. Underscores in
    # the leaf are preserved so nanopb-generated C struct names match
    # what we expect (e.g. demo.system → "demo_system_<Msg>").
    lines.append(f"package {package.replace('.', '_')};")
    lines.append("")

    for en in enums:
        lines.append(f"enum {en.name} {{")
        for v in en.values:
            lines.append(f"    {v.name} = {v.number};")
        lines.append("}")
        lines.append("")

    for msg in messages:
        lines.append(f"message {msg.name} {{")
        if not msg.fields:
            lines.append("    // empty body")
        for f in msg.fields:
            prefix = "repeated " if f.repeated else ""
            lines.append(f"    {prefix}{f.proto_type} {f.name} = {f.number};")
        lines.append("}")
        lines.append("")

    return "\n".join(lines) + "\n"


def generate_package_proto(art_path: str | Path,
                            out_root: str | Path) -> Path:
    """Parse a .art file, emit ONE .proto per package at the path
    mirroring the package name (dot → slash).

    Returns the written .proto path.
    """
    art_path = Path(art_path)
    out_root = Path(out_root)

    mm = metamodel_from_file(str(_GRAMMAR))
    model = mm.model_from_file(str(art_path))

    package = model.name or "artheia"
    pkg_parts = package.split(".")
    # File-on-disk leaf: use the last segment of the package as the
    # filename. demo.system → demo/system/system.proto.
    leaf = pkg_parts[-1]
    out_dir = out_root.joinpath(*pkg_parts)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{leaf}.proto"

    rendered = _render_proto(
        model,
        package=package,
        source_file=str(art_path),
    )
    out_file.write_text(rendered)
    return out_file
