"""Combine generated manifest modules (services.py + apps.py + their executor.py
sidecars) into one ``rig.py``.

``artheia gen-rig-combine <mod...> --out manifest/rig.py`` takes the per-cluster
manifest modules — each emitted by ``gen-manifest`` and exposing a
``<Cluster>Software`` :class:`SoftwareSpecification` + (via its sibling
executor.py) a ``SUPERVISORS`` list — and emits a generic combiner rig:

  * the SERVICES module's ``ServicesSoftware`` is the BASE (it carries the full
    platform supervisor tree with an empty ``app_sup`` mount);
  * every other module's ``*Software`` is ``.squash()``'d onto it;
  * the apps module's ``app_sup`` children fill the mount via an ``Override``;
  * ``<Rig> = <Combined>Software.to_rig()`` is the CLI entry the executor/manifest
    pipeline consumes.

Each ``<mod>`` is a Python module — given as a DOTTED path (``apps.manifest.
applications``) or a FILE path (``apps/manifest/applications.py``, converted to
the dotted form by walking up while ``__init__.py`` exists). The generated rig
imports each by its dotted name, so the modules must be importable at rig-import
time (on PYTHONPATH).
"""

from __future__ import annotations

import importlib
from pathlib import Path


def _to_module(spec: str) -> str:
    """A module SPEC → its dotted import path. Accepts a dotted name verbatim
    (``apps.manifest.applications``), or a FILE path that is converted to dotted
    form: the WORKSPACE-RELATIVE path with separators → dots and the ``.py``
    dropped (``services/manifest/service.py`` → ``services.manifest.service``).
    The path is taken relative to the workspace root (the nearest ancestor with
    MODULE.bazel / a .git, else cwd) so the dotted name matches how the editable
    package exposes it on PYTHONPATH."""
    if not (spec.endswith(".py") or "/" in spec or "\\" in spec):
        return spec
    p = Path(spec).resolve()
    root = None
    a = p.parent
    while a != a.parent:
        if (a / "MODULE.bazel").exists() or (a / ".git").exists() \
                or (a / "WORKSPACE").exists():
            root = a
            break
        a = a.parent
    base = root or Path.cwd().resolve()
    try:
        rel = p.relative_to(base)
    except ValueError:
        rel = Path(spec)
    return ".".join(rel.with_suffix("").parts)


def _software_symbol(module_dotted: str) -> "tuple[str, bool]":
    """Import the module and find its ``<Cluster>Software`` symbol +
    whether it's the SERVICES one (has the full tree / an app_sup mount).
    Returns (symbol_name, is_services). Raises if no *Software is found."""
    mod = importlib.import_module(module_dotted)
    softwares = [n for n in dir(mod) if n.endswith("Software")]
    if not softwares:
        raise ValueError(
            f"{module_dotted}: no '*Software' SoftwareSpecification found "
            f"(was it emitted by gen-manifest?)")
    # Prefer a single match; if several, the cluster-named one (skip aggregates).
    sym = sorted(softwares, key=len)[0]
    is_services = sym.lower().startswith("services") or "app_sup" in _tree_mounts(mod)
    return sym, is_services


def _tree_mounts(mod) -> "set[str]":
    """The supervisor-node names this module's SUPERVISORS declares (so we can
    tell the base tree — the one with an ``app_sup`` mount — from the apps
    sidecar)."""
    sup = getattr(mod, "SUPERVISORS", []) or []
    return {getattr(n, "name", "") for n in sup}


def _app_children(module_dotted: str) -> "list[str]":
    """The apps module's app_sup children = its ``*_SHORTS`` (every app member)."""
    mod = importlib.import_module(module_dotted)
    for n in dir(mod):
        if n.endswith("_SHORTS"):
            return list(getattr(mod, n))
    return []


_RIG_TEMPLATE = '''\
"""Combiner rig — GENERATED by `artheia gen-rig-combine`.

Merges the per-cluster manifest modules below into one deployable rig:
{module_list}
The SERVICES software is the base (full supervisor tree, empty app_sup); the
other clusters squash in; the apps fill app_sup. Regenerate with gen-rig-combine;
machine/endpoint specifics are deploy decisions you add to {rig}SpecLayer.
"""
from __future__ import annotations

from typing import cast

import dataclasses

from artheia.manifest.rig import Rig, SoftwareSpecification, VehicleIdentity
from artheia.manifest.transform import Append, SetTransformTypes
from typing import cast

{imports}
from {services_module} import SUPERVISORS as _SERVICES_TREE

# Base = the services software (carries the full platform supervisor tree with an
# empty `app_sup` mount).
_BASE = {base_software}

# The combined supervisor tree: the full services tree, with `app_sup`'s empty
# children replaced by this deployment's app members. (Same shape the platform
# rig builds by hand — fill the mount, Append the nodes.)
_APP_CHILDREN = {app_children!r}
{rig}_SUPERVISORS = [
    dataclasses.replace(n, children=list(_APP_CHILDREN)) if n.name == "app_sup"
    else n
    for n in _SERVICES_TREE
]

# The deploy delta: squash the apps software in (by same-identity) + set the
# combined tree. Add your machine / endpoint / vehicle specifics here.
{rig}SpecLayer = SoftwareSpecification(
    vehicle=VehicleIdentity(name="{vehicle}"),
    supervisors=cast(set[SetTransformTypes], {{
        Append(s) for s in {rig}_SUPERVISORS
    }}),
)

{rig}Software: SoftwareSpecification = (
    _BASE
{squashes}    .squash({rig}SpecLayer)
)

{rig}Rig: Rig = {rig}Software.to_rig()
'''


def write_rig_combine(modules: "list[str]", out_path: str,
                      rig_name: str | None = None,
                      vehicle: str | None = None,
                      force: bool = False) -> Path:
    """Emit the combiner rig.py from the manifest *modules*. Returns the path."""
    out = Path(out_path)
    if out.exists() and out.stat().st_size > 0 and not force:
        raise FileExistsError(f"{out} exists; pass --force to overwrite")

    dotted = [_to_module(m) for m in modules]
    # Classify each module: the services (base, full tree) vs the rest.
    base_mod = base_sym = None
    other = []          # (dotted, symbol)
    apps_mod = None
    for d in dotted:
        sym, is_services = _software_symbol(d)
        if is_services and base_mod is None:
            base_mod, base_sym = d, sym
        else:
            other.append((d, sym))
        if _app_children(d):
            apps_mod = d
    if base_mod is None:
        # No services module — use the first as base.
        base_mod, base_sym = dotted[0], _software_symbol(dotted[0])[0]
        other = [(d, s) for d, s in
                 ((dd, _software_symbol(dd)[0]) for dd in dotted[1:])]

    app_children = _app_children(apps_mod) if apps_mod else []
    rig = rig_name or (vehicle or "Combined").capitalize()
    veh = vehicle or rig.lower()

    imports = "\n".join(
        f"from {d} import {s}  # noqa: F401"
        for d, s in [(base_mod, base_sym), *other])
    squashes = "".join(f"    .squash({s})\n" for _d, s in other)
    module_list = "".join(f"#   {d}\n" for d in dotted)

    rendered = _RIG_TEMPLATE.format(
        module_list=module_list, imports=imports,
        base_software=base_sym, app_children=app_children,
        services_module=base_mod, rig=rig, vehicle=veh, squashes=squashes)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered)
    return out
