"""Per-process routing-table generator.

For each `composition` in an .art file, partition prototypes by their
`on process P` annotation. For each process P, emit a header listing
its NodeRefs:

    LocalRef<NodeType>                 local_name;     // owned here
    RemoteRef<NodeType, type, inst>    remote_name;    // peer

The TIPC (type, instance) for a remote ref comes from the referenced
NodeDecl's `tipc` block — the .art's per-node address IS the routing
address.

User code calls `cast(refs.counter, Inc{1})` or `call(refs.counter, ...)`
identically regardless of local vs remote. The cast/call overloads
on LocalRef vs RemoteRef pick the path at compile time.

Layout:

    <out>/<composition_name>__<process>_refs.hh

Each header is self-contained (just the typed members + an init helper
the process's main.cc calls at startup to bind local nodes and connect
to remote peers).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Dict, Optional

from textx import metamodel_from_file


_GRAMMAR = (Path(__file__).resolve().parent.parent /
            "grammar" / "artheia.tx")


@dataclass
class _NodeRef:
    proto_name: str        # name of the prototype in the composition
    node_type: str         # C++ class name (== .art node name)
    location: str          # "local" | "remote"
    tipc_type: str         # e.g. "0xd0010001"
    tipc_instance: int


@dataclass
class _Process:
    name: str
    refs: List[_NodeRef] = field(default_factory=list)


@dataclass
class _Composition:
    name: str
    processes: Dict[str, _Process] = field(default_factory=dict)


def _format_tipc_type(tipc) -> str:
    # tipc.type in the textX model is the literal string from the .art
    # (e.g. "0xd0010001"). Keep it as-is for direct use in C++ literals.
    t = tipc.type
    if isinstance(t, int):
        return f"0x{t:x}"
    return str(t)


def _harvest_composition(comp) -> _Composition:
    """Partition prototypes by `on process X`. A prototype without an
    `on process` annotation goes to a synthetic process named "default"
    (i.e. composition is single-process).

    Flattens nested-composition refs: an inner `composition Foo bar`
    contributes its prototypes verbatim at this composition's scope
    (inner names appear unprefixed — see model/flatten.py).
    """
    from artheia.model import flatten_composition
    proto_decls, _ = flatten_composition(comp)

    out = _Composition(name=comp.name)
    for el in proto_decls:
        # The grammar field for the new annotation is `process`. textX
        # leaves it as None if absent.
        proc = getattr(el, "process", None) or "default"
        node = el.type  # textX ref to NodeDecl
        ref = _NodeRef(
            proto_name=el.name,
            node_type=node.name,
            location="local",   # filled in per-process below
            tipc_type=_format_tipc_type(node.tipc),
            tipc_instance=int(getattr(node.tipc, "instance", 0) or 0),
        )
        out.processes.setdefault(proc, _Process(name=proc)).refs.append(ref)
    return out


def _render_header(comp: _Composition, this_process: str,
                    source_file: str) -> str:
    """Emit the routing header for one process within a composition."""
    self_proc = comp.processes[this_process]
    other_procs = [p for n, p in comp.processes.items() if n != this_process]

    lines: List[str] = []
    lines.append(f"// AUTO-GENERATED by `artheia gen-routing` — DO NOT EDIT")
    lines.append(f"// source: {source_file}")
    lines.append(f"// composition: {comp.name}")
    lines.append(f"// process: {this_process}")
    lines.append("//")
    lines.append("// Each prototype in the composition is either local to this")
    lines.append("// process (LocalRef — pass-by-value mailbox) or remote")
    lines.append("// (RemoteRef<NodeType, tipc_type, tipc_instance> — TIPC).")
    lines.append("// User code calls cast/call identically; overload resolution")
    lines.append("// picks the right path.")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include "NodeRef.hh"')
    lines.append("")
    # The node-type forward declarations are the responsibility of the
    # process's main.cc — it includes the relevant <Node>.hh headers
    # before pulling this routing header in. We list the C++ class
    # names we'll reference so any include omissions error early:
    used_types = {r.node_type for p in comp.processes.values() for r in p.refs}
    if used_types:
        lines.append("// Required upstream includes (each <NodeType>.hh):")
        for t in sorted(used_types):
            lines.append(f"//   class {t};")
        lines.append("")

    lines.append(f"namespace {comp.name.lower()}_routing {{")
    lines.append("")
    lines.append(f"struct {this_process}_Refs {{")

    for r in self_proc.refs:
        lines.append(f"    // local: owned by this process")
        lines.append(f"    demo::runtime::LocalRef<demo::{r.node_type}> {r.proto_name};")
    for p in other_procs:
        for r in p.refs:
            lines.append(f"    // remote: lives in process {p.name}")
            lines.append(
                f"    demo::runtime::RemoteRef<demo::{r.node_type}, "
                f"{r.tipc_type}u, {r.tipc_instance}u> {r.proto_name};"
            )

    lines.append("};")
    lines.append("")
    lines.append(f"}}  // namespace {comp.name.lower()}_routing")
    return "\n".join(lines) + "\n"


def generate_routing(art_path: str | Path,
                      composition_name: str,
                      out_dir: str | Path) -> List[Path]:
    """Parse the .art, find the named composition, emit one routing
    header per process declared in it. If no `on process` annotations
    are present the composition is treated as single-process and a
    single `default_refs.hh` is written."""
    art_path = Path(art_path)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    mm = metamodel_from_file(str(_GRAMMAR))
    model = mm.model_from_file(str(art_path))

    target = None
    for el in model.elements:
        if el.__class__.__name__ == "CompositionDecl" and el.name == composition_name:
            target = el
            break
    if target is None:
        raise ValueError(
            f"no composition named {composition_name!r} in {art_path}")

    comp = _harvest_composition(target)
    written: List[Path] = []
    for proc_name in comp.processes:
        rendered = _render_header(comp, proc_name, source_file=str(art_path))
        out_file = out_dir / f"{comp.name}__{proc_name}_refs.hh"
        out_file.write_text(rendered)
        written.append(out_file)
    return written
