"""Compile a per-rig trace-decoder subset.

Inputs: artheia's emitted netgraphs.
Output: one ``.cc`` registering decode+stringify function pairs in a
        message-name → handler table.

The motivation: PSP has ~4500 message types but a real rig only uses
~100. Compiling the full set into ``libtrace_decoder.so`` would bloat
every supdbg / supervisor-gui binary linking against it. This
generator takes the actual cluster netgraph (cluster signal routing)
+ the PSP / gateway netgraph (bus PDU routing) and emits decoders
ONLY for messages that appear in either.

Schema we consume:
  Cluster netgraph (`gen-netgraph`):
    {
      "package": "...",
      "nodes": [
        { "name": "...", "ports": [{"interface": "...", "messages": ["X","Y"]}, ...],
          "signals": { "MsgName": { "direction": "out", "destinations": [...] } } },
        ...
      ],
      "compositions": [
        { "connections": [{ "messages": ["X"], ... }] }
      ]
    }

  PSP netgraph (`gen-psp-netgraph`): per-bus PDU LUTs. Field naming
  differs (`pdu` / `msg_name` depending on flavour); we extract
  conservatively by name match on common keys.

Robot's trace adapter uses grpcio's Python reflection over the .proto
directly — it does NOT need this output. This generator is for C++
consumers (supdbg, supervisor-gui's trace panel).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable


_CC_TEMPLATE = '''\
// AUTO-GENERATED by `artheia gen-trace-decoder-subset` — DO NOT EDIT.
//
// Inputs:
//   cluster netgraph: {cluster_in}
//   psp netgraph:     {psp_in}
//
// Each entry below registers a (decode, stringify) pair for one
// message type. Built into libtrace_decoder.so; consumed by supdbg
// and supervisor-gui's trace panel.
//
// Total: {count} message types.

#include "platform/runtime/trace_decoder/registry.hh"

#include <string>

// One forward-declared handler per message — the actual decode/
// stringify routines live in nanopb-generated .pb.{{c,h}} files
// under platform/proto/. The handlers here are tiny shims that
// invoke the right pb_decode + a generic field printer.
namespace platform::runtime::trace_decoder {{

// Generic stringify driven by nanopb's pb_msgdesc_t — handler is
// just a fwd-decl; the dispatcher in registry.cc walks fields by
// descriptor. Listed message types are linked in via the .pb.h
// includes pulled by the per-message .cc files; if a message
// doesn't have a .pb.h under platform/proto, the link will fail
// loudly. That's the diagnostic — regenerate the proto subset.

extern const Handler kHandlers[];
extern const std::size_t kHandlerCount;

namespace {{
const Handler kEntries[] = {{
{entries}}};

[[gnu::used, gnu::constructor]]
void _register() {{
    for (std::size_t i = 0; i < sizeof(kEntries)/sizeof(kEntries[0]); ++i) {{
        register_handler(kEntries[i]);
    }}
}}
}}  // namespace

const Handler  kHandlers[] = {{}};   // dispatched via registry_, kept
const std::size_t kHandlerCount = 0; // for ABI parity if downstream
                                     // wants direct iteration.

}}  // namespace platform::runtime::trace_decoder
'''


def _collect_from_cluster(graph: dict) -> set[str]:
    """Union of message names appearing in a cluster netgraph.

    Walks two sources:
      - per-node ``signals`` dict keys (signal name == message type)
      - per-port ``messages`` list (interface-side message names)
      - per-composition connect ``messages``

    All three may overlap; the set is the union.
    """
    out: set[str] = set()
    for n in graph.get("nodes", []):
        for sig_name in n.get("signals", {}):
            out.add(sig_name)
        for port in n.get("ports", []):
            for m in port.get("messages", []):
                out.add(m)
    for comp in graph.get("compositions", []):
        for conn in comp.get("connections", []):
            for m in conn.get("messages", []):
                out.add(m)
    return out


def _collect_from_psp(graph: dict) -> set[str]:
    """Union of PDU / message names in a PSP / gateway netgraph.

    PSP netgraphs vary in flavour (per-bus dicts, flat tables). We
    pick conservatively: any string-valued key/field named ``msg``
    or ``pdu`` or ``signal`` or ``message`` becomes an entry.
    """
    out: set[str] = set()

    def _walk(obj: object) -> None:
        if isinstance(obj, dict):
            for k, v in obj.items():
                if k in ("msg", "pdu", "signal", "message") and isinstance(v, str):
                    out.add(v)
                _walk(v)
        elif isinstance(obj, list):
            for item in obj:
                _walk(item)

    _walk(graph)
    return out


def collect_message_types(
    *,
    cluster_netgraph: Path | str | None,
    psp_netgraph: Path | str | None,
) -> list[str]:
    """Return the sorted union of message types across both netgraphs.

    Either input may be ``None`` (e.g. a rig with no PSP-bus FCs has
    no gateway netgraph). At least one must be provided.
    """
    if cluster_netgraph is None and psp_netgraph is None:
        raise ValueError(
            "gen-trace-decoder-subset: at least one of --cluster-netgraph "
            "or --psp-netgraph must be given"
        )
    union: set[str] = set()
    if cluster_netgraph is not None:
        union |= _collect_from_cluster(
            json.loads(Path(cluster_netgraph).read_text())
        )
    if psp_netgraph is not None:
        union |= _collect_from_psp(
            json.loads(Path(psp_netgraph).read_text())
        )
    return sorted(union)


def _render_entries(msg_types: Iterable[str]) -> str:
    """Render the kEntries[] body — one Handler per msg type.

    Handler shape (defined in registry.hh):
      struct Handler {
          const char*    msg_type;
          DecodeFn       decode;     // pb_decode wrapper
          StringifyFn    stringify;  // pb-descriptor-walker
      };

    For each known msg type we register a sentinel that resolves at
    link time via the corresponding nanopb descriptor (extern). The
    actual decode/stringify routines come from platform/runtime/
    trace_decoder/, hand-written once and parameterised by the
    descriptor.
    """
    lines: list[str] = []
    for msg in msg_types:
        # Escape the msg_type for the C string literal. Names are
        # ASCII identifiers per artheia grammar — no escaping needed
        # beyond the bare-word check.
        if not msg.replace("_", "").isalnum():
            # Defensive: skip suspicious names rather than emit bad C++.
            continue
        lines.append(
            f'    {{ "{msg}", &decode_by_name, &stringify_by_name }},'
        )
    return "\n".join(lines) + ("\n" if lines else "")


def generate(
    *,
    cluster_netgraph: Path | str | None,
    psp_netgraph: Path | str | None,
    out_file: Path | str,
) -> Path:
    """Write the trace-decoder-subset .cc.

    Returns the output path.
    """
    msg_types = collect_message_types(
        cluster_netgraph=cluster_netgraph,
        psp_netgraph=psp_netgraph,
    )
    cc = _CC_TEMPLATE.format(
        cluster_in=str(cluster_netgraph) if cluster_netgraph else "(none)",
        psp_in=str(psp_netgraph) if psp_netgraph else "(none)",
        count=len(msg_types),
        entries=_render_entries(msg_types),
    )
    p = Path(out_file)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(cc)
    return p
