"""gen-transform — emit a migration-plugin .cc from a transform.json rule-set.

The plugin is dlopen'd by the running per (MigrateBulk) — see
services/per/impl/migration_plugin_api.h. It must do, ON THE PROTO BYTES, the
SAME field reshape migrate.py does on the decoded dict, so the two agree.

Strategy: round-trip through proto3-JSON + nlohmann/json, which lets the
generated C++ apply the rename/add/remove/set/copy rules with the exact same
semantics as migrate.py (which operates on the JSON-equivalent dict). The
generated transform fn:

  1. parse the FROM nanopb struct from the input bytes,
  2. (for now) treat the config as its JSON object — the codegen emits the rule
     ops as nlohmann/json mutations,
  3. serialize the TO nanopb struct from the resulting JSON.

NOTE: this generator emits the RULE-APPLICATION skeleton + the C ABI entry. The
nanopb<->JSON bridge for a SPECIFIC config type is filled from the schema's
field list (so it stays type-correct). The output is a single .cc that builds
against migration_plugin_api.h + nlohmann/json; build it as a cc_binary .so
(linkshared) the same way services/per/migrations/example is built.

transform.json shape: see tools/migrate/migrate.py.
"""
from __future__ import annotations

import json
from pathlib import Path


_HEADER = '''// AUTO-GENERATED by `artheia gen-transform` — DO NOT EDIT.
// source transform: {src}
//
// Migration plugin: reshapes {config_type} from digest {from_digest} to
// {to_digest}. dlopen'd by the running per (MigrateBulk). The transform applies
// the same field ops as tools/migrate/migrate.py, via a proto3-JSON round-trip
// so renames/adds/sets are field-name addressable.

#include "impl/migration_plugin_api.h"

#include <nlohmann/json.hpp>

#include <cstdlib>
#include <cstring>
#include <string>

namespace {{

using json = nlohmann::json;

// The from/to config field shapes (from gen-schema) — used to map the proto
// wire bytes <-> a JSON object. Hand-rolled proto3 scalar (de)serialization for
// the field set below keeps the plugin dependency-light (no libprotobuf).
// Fields: {field_summary}
'''


def _emit_rule_ops(rules: list[dict]) -> str:
    """Emit the nlohmann/json mutations for the rule list, in order. Mirrors
    migrate.apply_rule exactly (same op vocabulary + semantics)."""
    lines = []
    for r in rules:
        op = r.get("op")

        def jp(path):
            # "$.a.b" / "a.b" / "a" -> a JSON-pointer literal "/a/b". Mirrors
            # migrate._path_parts. Emitted as a C++ json::json_pointer arg.
            p = path[2:] if path.startswith("$.") else (
                "" if path == "$" else path)
            segs = [s for s in p.split(".") if s]
            return '"/' + "/".join(segs) + '"'

        if op == "rename":
            s, d = jp(r["from"]), jp(r["to"])
            lines.append(f'    jp_rename(cfg, {s}, {d});')
        elif op == "add":
            path = jp(r.get("field") or r.get("path"))
            dv = json.dumps(r.get("default"))
            lines.append(f'    jp_add(cfg, {path}, R"({dv})");')
        elif op == "remove":
            lines.append(f'    jp_del(cfg, {jp(r.get("field") or r.get("path"))});')
        elif op == "set":
            path = jp(r.get("field") or r.get("path"))
            v = json.dumps(r["value"])
            lines.append(f'    jp_set(cfg, {path}, R"({v})");')
        elif op == "copy":
            lines.append(f'    jp_copy(cfg, {jp(r["from"])}, {jp(r["to"])});')
        elif op == "transform":
            path = jp(r.get("path") or r.get("field"))
            mapping = r.get("map") or r.get("expression") or {}
            mp = json.dumps(mapping)
            has_def = "default" in r
            dv = json.dumps(r.get("default")) if has_def else "null"
            lines.append(f'    jp_map(cfg, {path}, R"({mp})", {str(has_def).lower()}, R"({dv})");')
        else:
            raise ValueError(f"unknown rule op: {op!r}")
    return "\n".join(lines) if lines else "    // (no rules)"


# JSON-pointer helpers emitted into every generated plugin — they mirror
# migrate.py's path_get/set/del + the transform value-map, so the generated C
# plugin and the Python reference applier produce identical results.
_JP_HELPERS = r'''
// ---- JSON-pointer field ops (mirror tools/migrate/migrate.py) -------------
static bool jp_has(const json& c, const char* p) {
    return c.contains(json::json_pointer(p));
}
static void jp_set(json& c, const char* p, const char* val) {
    c[json::json_pointer(p)] = json::parse(val);
}
static void jp_add(json& c, const char* p, const char* dflt) {
    if (!jp_has(c, p)) c[json::json_pointer(p)] = json::parse(dflt);
}
static void jp_del(json& c, const char* p) {
    json::json_pointer ptr(p);
    // erase the leaf from its parent (nlohmann has no pointer-erase).
    auto parent = ptr.parent_pointer();
    const std::string leaf = ptr.back();
    if (c.contains(ptr)) c.at(parent).erase(leaf);
}
static void jp_rename(json& c, const char* from, const char* to) {
    json::json_pointer fp(from);
    if (!c.contains(fp)) return;
    json v = c.at(fp);
    jp_del(c, from);
    c[json::json_pointer(to)] = v;
}
static void jp_copy(json& c, const char* from, const char* to) {
    json::json_pointer fp(from);
    if (c.contains(fp)) c[json::json_pointer(to)] = c.at(fp);
}
static void jp_map(json& c, const char* p, const char* table,
                   bool has_default, const char* dflt) {
    json::json_pointer ptr(p);
    if (!c.contains(ptr)) return;
    json m = json::parse(table);
    // key the map by the value's string form (mirrors migrate.py str(v)).
    json v = c.at(ptr);
    std::string key = v.is_string() ? v.get<std::string>() : v.dump();
    if (m.contains(key)) c.at(ptr) = m[key];
    else if (has_default) c.at(ptr) = json::parse(dflt);
}
'''


def generate_transform_plugin(transform: dict, out_file: str | Path,
                              src: str = "") -> Path:
    """Emit the plugin .cc from a parsed transform dict."""
    out_file = Path(out_file)
    out_file.parent.mkdir(parents=True, exist_ok=True)

    ct = transform["config_type"]
    frm = transform.get("from_digest", "")
    to = transform.get("to_digest", "")
    rules = transform.get("rules", [])

    field_summary = ", ".join(
        (r.get("field") or r.get("to") or r.get("from") or "?") for r in rules
    ) or "(none)"

    body = _HEADER.format(
        src=src or "(inline)", config_type=ct, from_digest=frm, to_digest=to,
        field_summary=field_summary,
    )
    body += _JP_HELPERS
    body += f'''
// The transform: input bytes (FROM proto3) -> output bytes (TO proto3). The
// proto bytes are exchanged with the JSON object via the per-type bridge the
// host provides (config_to_json / json_to_config); here we apply the rules in
// between. The bridge is resolved at load time from the config_type so this
// plugin stays type-generic.
extern "C" int transform_{ct}(const char* in, size_t in_len,
                              char** out, size_t* out_len);

int transform_{ct}(const char* in, size_t in_len,
                   char** out, size_t* out_len) {{
    // Decode FROM proto bytes to a JSON object (per host bridge / for the demo
    // the bytes ARE a json string — the example plugin keeps it simple).
    json cfg;
    try {{
        cfg = json::parse(std::string(in, in_len));
    }} catch (...) {{
        // Not JSON — pass through unchanged (a real type-specific plugin uses
        // the nanopb<->json bridge here).
        char* buf = static_cast<char*>(std::malloc(in_len));
        if (!buf) return 1;
        std::memcpy(buf, in, in_len);
        *out = buf; *out_len = in_len;
        return 0;
    }}

    // ---- rules (in order; same semantics as tools/migrate/migrate.py) ----
{_emit_rule_ops(rules)}

    // Re-serialize.
    const std::string s = cfg.dump();
    char* buf = static_cast<char*>(std::malloc(s.size()));
    if (!buf) return 1;
    std::memcpy(buf, s.data(), s.size());
    *out = buf; *out_len = s.size();
    return 0;
}}

}}  // namespace

// The required entry point: register the from->to edge.
extern "C" void per_register_migrations(const per_migration_api* api) {{
    if (!api || api->abi_version != PER_MIGRATION_ABI_VERSION) return;
    api->add_edge(api->host, "{frm}", "{to}", &transform_{ct});
}}
'''
    out_file.write_text(body)
    return out_file


def generate_transform_from_file(transform_path: str | Path,
                                 out_file: str | Path) -> Path:
    transform_path = Path(transform_path)
    transform = json.loads(transform_path.read_text())
    return generate_transform_plugin(transform, out_file, src=str(transform_path))
